# [REQUIRED] OAuth 2.0 client identifier valid at the authorization server.
# https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1
client_id = "m0dfcl4aX3qshMnXrng67qGHZBS9mJ1zxv"

# [REQUIRED] A secret to verify the OpenID nonce used to mitigate replay attacks.
# https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest
# It must be sufficiently random to not be guessable.
nonce_secret = "e8ioOPMp/Yx+ZznomfrYtjaqIxT2iSRH1pAFlHDtnPM="

# [OPTIONAL] Whether to verify the access token using the OpenID userinfo endpoint.
# https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.3
# Used to introspect opaque and other types of tokens revocable by the authorization server.
# If revocation is not a concern – or when IdP rate limits are –
# comment out this option to validate JWT access tokens at the edge.
# https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.16.8
# Defaults to false if omitted.
introspect_access_token = true

# [OPTIONAL] Whether the access token is a JWT.
# https://tools.ietf.org/html/rfc7519
# JWT access tokens may be validated at the edge, using an approach similar to ID tokens.
# Relevant only when validate_access_token = false. Defaults to false if omitted.
# jwt_access_token = false

# [OPTIONAL] client_secret parameter for certain Identity Providers' token endpoint.
# Google, for example, requires the client secret obtained from its API console: 
# https://developers.google.com/identity/protocols/oauth2/native-app#exchange-authorization-code
# WARNING: Including this parameter produces NON-NORMATIVE OAuth 2.0 token requests:
# https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.3.1
# client_secret = "SOME_CLIENT_SECRET"

# [OPTIONAL] Path for the redirection URI to which OAuth 2.0 responses will be sent. 
# https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.1
# Defaults to /callback if omitted.
# callback_path = "/callback"

# [OPTIONAL] PKCE code challenge method.
# https://tools.ietf.org/html/rfc7636#section-4.3
# Defaults to S256 if omitted.
# code_challenge_method = "S256"

# [OPTIONAL] Length of an arbitrary alphanumeric suffix added to the 
# parameter used to maintain state between the request and the callback.
# Defaults to 10 if omitted.
# state_parameter_length = 10

# [OPTIONAL] OAuth 2.0 scope list (one or more space-separated scopes).
# https://oauth.net/2/scope
# Defaults to openid if omitted.
# scope = "openid"
